# Generated by Django 2.2 on 2022-06-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Login', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=30)),
                ('Nickname', models.CharField(max_length=25)),
                ('Vallue', models.PositiveIntegerField(default=0, max_length=30)),
                ('Valluepr', models.PositiveIntegerField(default=0, max_length=15)),
                ('Build1', models.PositiveIntegerField(default=0, max_length=6)),
                ('Build2', models.PositiveIntegerField(default=0, max_length=6)),
            ],
        ),
    ]
